module:
  imports:
    - path: github.com/basa-casa/admin
  mounts:
    - source: src/schemas
      target: assets/schemas
    - source: data
      target: data
    - source: content
      target: content