baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"

# Remove files from destination not found in static directories
cleandestinationdir = true
renderToDisk = true
enableEmoji = true
disableFastRender = true
enableGitInfo = false
disableKinds = ["taxonomy", "home", "RSS", "sitemap", "robotsTXT", "404"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  mainSections = ["posts"]

  # css = ["bmfw.css"] # default = ["bmfw.css", "ox-hugo.css"]
  # js = []

  [Params.source]
    url = "https://github.com/basa-casa/admin" # Mandatory

[module]
  [[module.imports]]
    path = 'github.com/basa-casa/admin-scms'
  [[module.imports]]
    path = 'github.com/basa-casa/no-class'
  [[module.mounts]]
    source = 'content'
    target = 'content'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'data'
    target = 'data'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
